server:
  address: localhost
  port: 8080
  context-path: /
  compression:
    enabled: true
  connection-timeout: 60000

mysql:
  db-url: jdbc:mysql://localhost:3306/zyf
  jdbc-name: com.mysql.jdbc.Driver
  user-name: root
  password: qq125680
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyf
    username: root
    password: qq125680
  http:
    converters:
      preferred-json-mapper:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.model
#  config: classpath:mybatis-config.xml
#  type-handlers-package: com.example.mapper

#mapper:
#  mappers: com.example.mapper
#  not-empty: false
#  identity: MYSQL: